import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { CabinIDProvider } from '@cabin-id/nextjs';

import UseQueryProviders from "@/providers/use-query-provider";

import "./globals.css";

import {
	Pathway_Extreme,
	Bungee,
	Inter,
	Bungee_Inline,
	Bungee_Shade,
	Phudu,
	League_Gothic,
	Faster_One,
	Cabin
} from "next/font/google";

const pathwayExtreme = Pathway_Extreme({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-pathwayExtreme",
	display: "swap",
	adjustFontFallback: false,
});

const interFont = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-inter",
});

const bungee = Bungee({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-bungee",
});

const bungeeInline = Bungee_Inline({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-bungeeInline",
});

const bungeeShade = Bungee_Shade({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-bungeeShade",
});

const phudu = Phudu({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-phudu",
});

const leagueGothic = League_Gothic({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-leagueGothic",
});

const calSans = LocalFont({
	src: "../public/fonts/CalSans-SemiBold.ttf",
	variable: "--font-calsans",
});

const fasterOne = Faster_One({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-fasterOne",
});


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<CabinIDProvider>
				<UseQueryProviders>
					<body
						className={`${pathwayExtreme.variable} ${bungee.variable} ${bungeeShade.variable} ${interFont.variable} ${bungeeInline.variable} ${phudu.variable} ${leagueGothic.variable} ${calSans.variable} ${fasterOne.variable}`}
					>
						{children}
					</body>
				</UseQueryProviders>
			</CabinIDProvider>
		</html>
	);
}
